### ISSUE TITLE
RFE: activate___() method on publisher/subscriber

### ISSUE THREAD

**Issue by quartzgithub** [reactive-streams/reactive-streams-jvm#303] opened 2016-02-09 02:55 UTC
The construction of the streams require a fixed programmatic sequence ensuring that the publisher be created before the subscriber can subscribe to it. 

In the interest of initializing publishers and subscribers from a file or other persisted form, an arbitrary framework implementation could have some stream connectivity cfg to hook subscribers to publishers. However, such framework might prefer to only instanciate publishers/subscribers/processors in random order, and let them perform their lookup when all instanceof Publisher are installed. Obviously the subscriber's constructor MUST NOT lookup a publisher, since this Publisher might not be there yet.

In such framework, on top of the fact that Publishers are be expected to start by themselves on construction (or perhaps because the instance implements Runnable), this is rather unclean, particularly if anyone considers serialization for these classes.

I'm suggesting to add `Subscriber.activateSubscriber()` and `Publisher.activatePublisher()` (distinct signature to avoid clashing in `Processor` multiple inheritance) to clarify the startup sequence. We can consider extending the interfaces instead, like `ActivatablePublisher|ActivatableSubscriber`.

**Comment by viktorklang** [comment] 2016-02-17 20:29
@quartzgithub It is by design that Publishers are unaware of Subscribers and vice versa, this makes it possible to orchestrate discovery at a higher level, something which is required in any such case is addressibility, which is simplest to leave open to best fit with the discovery mechanism chosen.

Does that make sense?

**Comment by smaldini** [comment] 2016-02-18 07:50
An alternative is to implement a containing Publisher orchestrating Processor and publisher chain selection, e.g. reactor uses [RSC Multicast or Publish operator for this](https://github.com/reactor/reactive-streams-commons/blob/master/src/test/java/reactivestreams/commons/publisher/ConnectablePublisherMulticastTest.java), derived from Rx connectable observable pattern.

**Comment by viktorklang** [comment] 2016-02-18 08:26
Stéphane, good point, it could also be exposed as a Processor!

-- 
Cheers,
√

**Comment by viktorklang** [comment] 2016-03-01 08:43
I'm closing this Issue as a "Wontfix". Please reopen if you want to discuss further, thank you

**Closed by viktorklang** 2016-03-01 08:43 UTC
