### ISSUE TITLE
Propose a new TCK Base test class for combined tests

### ISSUE THREAD

**Issue by smaldini** [reactive-streams/reactive-streams-jvm#242] opened 2015-03-13 18:44 UTC
Hi folks,

That would be awesome if we had a test similar to IdentityProcessorTests to do this instead of createIdentityProcessor() : 
```java
@Override
public Processor[] createProcessors(){
  return new Processor[]{ akkaStreamProcessor1(), reactorProcessor1(), akkaStreamProcessor2(), reactorProcessor2()} };
}
```
Tested outcome:
```java
// akka1 -> reactor1 -> akka2 -> reactor2
akkaStreamProcessor2.subscribe(reactorProcessor2);
reactorProcessor1.subscribe(akkaStreamProcessor2);
akkaStreamProcessor1.subscribe(reactorProcessor1);
helperPublisher.subscribe(akkaStreamProcessor1);

// akka2 -> reactor1 -> akka1 -> reactor2
akkaStreamProcessor1.subscribe(reactorProcessor2);
reactorProcessor1.subscribe(akkaStreamProcessor1);
akkaStreamProcessor2.subscribe(reactorProcessor1);
helperPublisher.subscribe(akkaStreamProcessor2);

//...
```
This will shuffle all combinations possible of ordering, subscribe each other and pass the same ProcessorTests to the whole (and optionally, individually). That would help testing tck in more fine-grained way for the non trivial pipelines. Ofc mathematically in theory the order shouldn't affect the outcome, but that would hold true if there are no side effect left untested by simple processor tests. However that would be quite a shortcut for implem which usually come with a set of operations (so possibly Processor) to verify them in a single class very easily.
In the same spirit we can also shuffle Helper Publisher if wished.
Plus Test Metrics in Sonar or others will be super cool with a N^M number of tests generated :dancer:

**Comment by ktoso** [comment] 2015-03-13 19:02
I believe this is basically what we had proposed in https://github.com/reactive-streams/reactive-streams-jvm/issues/112 already :-)

**Comment by viktorklang** [comment] 2015-03-14 16:21
@smaldini Agreed! It would be nice with a "integration" subproject where we can validate that things work well together.

**Comment by viktorklang** [comment] 2015-03-30 09:09
Closing as duplicate of https://github.com/reactive-streams/reactive-streams-jvm/issues/112 :)

**Closed by viktorklang** 2015-03-30 09:09 UTC
Labels: enhancement
