### ISSUE TITLE
Any plans for reactive-streams-jvm9?

### ISSUE THREAD

**Issue by rotilho** [reactive-streams/reactive-streams-jvm#366] opened 2017-05-05 13:50 UTC
Java 9 is about to be released, are there any plans to provide reactive-streams-jvm to Java 9?

All interfaces could easily extend Java 9 ones and make it compatible.

**Comment by viktorklang** [comment] 2017-05-05 14:18
:)

Duplicate of https://github.com/reactive-streams/reactive-streams-jvm/issues/294

**Closed by viktorklang** 2017-05-05 14:18 UTC
